#Position constants to be put in the const_list argument of the
#AttributeSelector constructor. Each group corresponds to a seperate list.
X_POS_LABEL_X = 50
X_POS_LABEL_Y = 0
X_POS_FIELD_X = 230
X_POS_FIELD_Y = 10
X_POS_BUTTON_UP_X = 270
X_POS_BUTTON_UP_Y = 10
X_POS_BUTTON_DOWN_X = 195
X_POS_BUTTON_DOWN_Y = 10

Y_POS_LABEL_X = 50
Y_POS_LABEL_Y = 50
Y_POS_FIELD_X = 230
Y_POS_FIELD_Y = 60
Y_POS_BUTTON_UP_X = 270
Y_POS_BUTTON_UP_Y = 60
Y_POS_BUTTON_DOWN_X = 195
Y_POS_BUTTON_DOWN_Y = 60

X_VEL_LABEL_X = 250
X_VEL_LABEL_Y = 0
X_VEL_FIELD_X = 430
X_VEL_FIELD_Y = 10
X_VEL_BUTTON_UP_X = 470
X_VEL_BUTTON_UP_Y = 10
X_VEL_BUTTON_DOWN_X = 395
X_VEL_BUTTON_DOWN_Y = 10

Y_VEL_LABEL_X = 250
Y_VEL_LABEL_Y = 50
Y_VEL_FIELD_X = 430
Y_VEL_FIELD_Y = 60
Y_VEL_BUTTON_UP_X = 470
Y_VEL_BUTTON_UP_Y = 60
Y_VEL_BUTTON_DOWN_X = 395
Y_VEL_BUTTON_DOWN_Y = 60

ENERGY_LABEL_X = 458
ENERGY_LABEL_Y = 0
ENERGY_FIELD_X = 645
ENERGY_FIELD_Y = 10
ENERGY_BUTTON_UP_X = 685
ENERGY_BUTTON_UP_Y = 10
ENERGY_BUTTON_DOWN_X = 610
ENERGY_BUTTON_DOWN_Y = 10

ADD_BALL_BUTTON_X = 600
ADD_BALL_BUTTON_Y = 60
