#Constants to be used in the AttributeSelector class
LABEL_WIDTH = 200
LABEL_HEIGHT = 50

FIELD_WIDTH = 40
FIELD_HEIGHT = 30

UP_BUTTON_WIDTH = 35
UP_BUTTON_HEIGHT = 30
DOWN_BUTTON_WIDTH = 35
DOWN_BUTTON_HEIGHT = 30

LABEL_X = 0
LABEL_Y = 1
UP_X = 2
UP_Y = 3
DOWN_X = 4
DOWN_Y = 5
FIELD_X = 6
FIELD_Y = 7
